default_config:

logger:
  default: warning
  logs:
    synergy: warning
    custom_components.synergy.datacoordinator: debug
    custom_components.synergy.sensor: debug
    custom_components.synergy.updates: debug
    custom_components.synergy.fixes: debug
    homeassistant_historical_sensor: debug
